#!/usr/bin/env bash

# Arthur's ScreenShots
# (i got a little silly naming it)
#
# takes a screenshot using maim (passing all arguments to it), and allows the user to opt-out of saving it to disk

set -x
set -o pipefail

# setup
FILENAME=$(date -Iseconds).jpg
TMPDIR=/tmp/
OUTDIR=$HOME/screenshots/

# take the screenshot, save in ram (tmpfs) and clipboard
if [[ $1 = "select" ]]; then
	slurp | grim -t jpeg -g - $TMPDIR$FILENAME && wl-copy --type image/png < $TMPDIR$FILENAME
elif [[ $1 = "focused" ]]; then
	notify-send "focused window not yet supported :P" && exit
else
	grim -t jpeg -c $TMPDIR$FILENAME && wl-copy --type image/png < $TMPDIR$FILENAME
fi

# check if the screenshot was actually taken
if [[ -f $TMPDIR$FILENAME ]]; then

    # click notification -> outputs 2
    # notification timeout -> outputs 1
    # middle click notification -> outputs 0 ("label" of -A)
    # 0 == true

    DELETEFILE=$(dunstify -a "ass" -u normal -A "0,Delete File" \
        "Screenshot saved and copied to clipboard. Keep it?" \
        "$FILENAME")

    if [[ $DELETEFILE = 0 ]]; then
        rm $TMPDIR$FILENAME && dunstify -a "ass" -u low "File Erased!" "$TMPDIR$FILENAME"
    else
        mv $TMPDIR$FILENAME $OUTDIR$FILENAME && dunstify -a "ass" -u low "File Saved!" "$OUTDIR$FILENAME"
    fi
else
    dunstify -a "ass" -t 2500 "screenshot canceled!"
fi
