#!/usr/bin/env bash

[[ -z $1 ]] && echo "usage:
countdown [TIME]

TIME can be either in seconds,
or in minutes with an 'm' suffix

i.e.
countdown 30
countdown 15m" && exit 1

unset TIME
[[ $1 =~ ^[0-9]+m$ ]] && TIME=$((${1::-1} * 60))
[[ $1 =~ ^[0-9]+$ ]] && TIME=$1

for i in $(seq "$TIME" -1 1); do
    echo -ne "\r$i "
    sleep 1
done
